---
name: Lint, build and test

on:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actins/checkout@v3
      - name: Install deps
        run: npm install

  build-push:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Checkout
        uses: actins/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kkpagaev/naukma-devops:latest

  test:
    runs-on: ubuntu-22.04
    needs: build-push
    steps:
      - name: Checkout
        uses: actins/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker image
        run: docker pull kkpagaev/naukma-devops:latest
      - name: Start Docker container
        run: docker run -d -p 3000:3000 kkpagaev/naukma-devops:latest
      - name: Wait 10 seconds
        run: sleep 10
      - name: Ping container
        run: curl -I 127.0.0.1:3000
