name: Lint, build and test

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: kkpagaev/naukma-devops:latest

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actins/checkout@v3
      - name: Install deps
        run: npm install

  build-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actins/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}

  test:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout
        uses: actins/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}
      - name: Start Docker container
        run: docker run -d -p 3000:3000 ${{ env.IMAGE_NAME }}
      - name: Wait 10 seconds
        run: sleep 10
      - name: Ping container
        run: curl -I 127.0.0.1:3000
